### ISSUE TITLE
why does this utility need the file vault to be off?

### ISSUE THREAD

**Issue by kibin** [cormiertyshawn895/RecordingIndicatorUtility#1]
<img width="462" alt="Screenshot 2022-02-11 at 11 48 33 PM" src="https://user-images.githubusercontent.com/1782569/153667945-d1e0340e-798f-4280-847e-af8df670775c.png">

**Comment by kibin** [comment]
found it FAQ, closing

**Comment by cormiertyshawn895** [comment]
With [the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases), you no longer need to turn off FileVault or `authenticated-root`. Turning off SIP is now enough for Recording Indicator Utility to work its magic. The QR code instruction within the app has also been updated.

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
