### ISSUE TITLE
Not working on M1 Macbook Air on Ventura 13.0

### ISSUE THREAD

**Issue by thelazurus** [cormiertyshawn895/RecordingIndicatorUtility#10]
Title says it really, when trying to set this up on my m1 air running Ventura, I go through the RecoveryOS part of setup, where you disable csrutil, after that the system no longer boots, instead bootlooping for a while until coming to a "Your system is damaged and macOS needs to be reinstalled" screen.

Luckily, reenabling SIP seemed to get things going again, but I wanted to make sure I reported this.

Thanks!

**Comment by AliahX** [comment]
i have this same problem on an m2 macbook pro running montery. it scared the fuck out of me lmao

**Comment by cormiertyshawn895** [comment]
Hi thelazurus and AliahX,

Based on your feedback, I've improved Recording Indicator Utility to be more reliable. With [the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases), you no longer need to turn off FileVault or `authenticated-root`. Turning off SIP is now enough for Recording Indicator Utility to work its magic. The QR code instruction within the app has also been updated.

Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
