### ISSUE TITLE
Mac Mini 12.6.0 won't boot, "macOS must repaired", after following instructions

### ISSUE THREAD

**Issue by cybrgloom** [cormiertyshawn895/RecordingIndicatorUtility#12]
Hi there,

I went through the disabling SIP steps as outlined, followed all instructions to the letter, the terminal commands reported success. Then upon restart, the system consistently would not boot, it halted every time shortly after every restart with the error "Your system is corrupt, macOS must be reinstalled". (Sorry forgot to write down the exact error text, it wasn't the word "corrupt" but something similar.) Then it always went into the Recovery environment, with the only option of a full reinstall (no "repair" option). 

I then reversed the steps of the SIP instructions, did a "csrutil enable", and then the system booted okay again. Though, of course can't get rid of the dot. 

This is on a Mac Mini M1, macOS 12.6.0. I'm aware there is a 12.6.3. I might be able to update this weekend and give it another go, but got quite a scare from this.... 

I see others reporting the same with no replies. Has anyone done this successfully with either 12.6.0 or 12.6.3?

Interestingly, it worked okay on my Macbook Pro M1 which is currently on 12.6.1, no orange dot there, so it will stay on 12.6.1 for as long as possible!! :) My experience so far is that I've had to disable SIPs every time the system updates macOs.

**Comment by denzakharov** [comment]
Same for me, had to re-install macOS after that. M1 MacBook Pro, macOS 13.2.1.

**Comment by cormiertyshawn895** [comment]
Hi cybrgloom, pmjm and denzakharov,

Based on your feedback, I've improved Recording Indicator Utility to be more reliable. With [the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases), you no longer need to turn off FileVault or `authenticated-root`. Turning off SIP is now enough for Recording Indicator Utility to work its magic. The QR code instruction within the app has also been updated.

Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by cybrgloom** [comment]
Thank you, I will give this a try. Currently travelling (without the Mac
Mini), will give it a spin next week when I'm back in the studio.

**Comment by cybrgloom** [comment]
Okay! Tried the new version now on a Mac Mini running macOS 12.6.0, this
version seems to work. I could disable SIPS and restart the system without
any error messages. Turning the indicator light on/off seems to work (I
don't have an external screen available right now to verify it works on
external HDMI output, but it the dot no longer appears on the menu bar so I
assume will also work on external screens - will report back if this is not
the case)

There is however a peculiar problem that might or might not be related -
I'm unable to update from 12.6.0 to 12.6.3, the update process fails
immediately with "A snapshot is currently set to boot..." and a longer
error message. I've tried restarting multiple times, and tried the update
both before and after disabling SIPS / turning on/off indicator light. This
might not be related to RIU but thought I'd mention it, perhaps it could
explain why we're having troubles. For, all is good, I'm okay with 12.6.0
for now, everything works, more important to get rid of the indicator light
than anything else, I can stay on 12.6.0 until I'm forced to 13 or 14 by an
inevitable app or service update :)

Thanks for the update and your work on this.

**Comment by cormiertyshawn895** [comment]
If you are having difficulty updating from macOS 12.6 to macOS 12.6.3 in System Preferences, you can download the full macOS 12.6.3 installer from the App Store:
https://apps.apple.com/app/macos-monterey/id1576738294
https://mrmacintosh.com/macos-12-monterey-full-installer-database-download-directly-from-apple/

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
