### ISSUE TITLE
"Failed to disable the authenticated root requirement"

### ISSUE THREAD

**Issue by jaaaamIron** [cormiertyshawn895/RecordingIndicatorUtility#13]
Currently following the step by step instructions on the QR code, and get this warning when I try to enable sealed snapshots. Any ideas?

**Comment by cormiertyshawn895** [comment]
[Recording Indicator Utility 2.0](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases/tag/2.0) no longer requires you to make changes to sealed snapshots.

If you are already using the latest version of Recording Indicator Utility, can you post a photo or screenshot of the warning or error?

**Comment by jaaaamIron** [comment]
Hi - I think I must've found my way onto an outdated version of the step by step guide. It's all working now, thanks!
