### ISSUE TITLE
App doesn't work and I get a system error on start up

### ISSUE THREAD

**Issue by CarlosUnchained** [cormiertyshawn895/RecordingIndicatorUtility#14]
Hello,

After disabling security on my Mac and opening the app a pop up ask for the password, then it says the following: Turning off the recording indicator light requires a restart to take effect.

This happens every time I restart, so it takes no effect and the app doesn't work.

Additionally I get a popup on start up from the system, System Extension Error that looks like this:
https://discussions.apple.com/thread/253338157

I'm stuck now since I can't use your app and the error always appears.

Can you help me either removing your app or making it work properly?

Thanks.

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
