### ISSUE TITLE
Feature Request: Hide Mic Mode Icon

### ISSUE THREAD

**Issue by jonescamilla** [cormiertyshawn895/RecordingIndicatorUtility#15]
I am yet to fully try out this application but would love the ability to hide the Mic Mode Icon in the Menu Bar. 
![image](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/assets/61066815/e1971525-e2fe-49e7-927c-06053de98fc5)
![image](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/assets/61066815/36394401-62d8-4db7-9235-affc89c2e403)

When encorporating this feature I would love the option to toggle which icon is hidden. I appreciate the icon alerting me of my microphone being collected by an app. However I will never use the Mic Mode feature and would like to turn that functionality off.

Thank you!

**Comment by cormiertyshawn895** [comment]
Recording Indicator Utility has been discontinued. In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
