### ISSUE TITLE
Video effects for Continuity Camera hidden

### ISSUE THREAD

**Issue by jrucho** [cormiertyshawn895/RecordingIndicatorUtility#16]
Hi! Just found out that the app hide the Continuity Camera video effects when enabled in macOS Sonoma. When it is deactivated the effects appear again in the menu bar.

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
