### ISSUE TITLE
Not working on Monterey 12.7.1

### ISSUE THREAD

**Issue by minkpan** [cormiertyshawn895/RecordingIndicatorUtility#17]
It's my own foolish fault for not checking it on one system before also updating the other, but I can confirm that this is no longer working on this version of Monterey, and the dreaded Orange Dot is back while I've got a zoom meeting on the same computer. I've tested on 2 machines. It has also stopped working on my 3rd computer, which is running Ventura 13.6.1, but thankfully I only use that one to push, not to capture.

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
