### ISSUE TITLE
Unable to update macOS, fails with "boot snapshot" error - RIU / SIP problem?

### ISSUE THREAD

**Issue by cybrgloom** [cormiertyshawn895/RecordingIndicatorUtility#18]
Hello, appreciate this tool so much! 

I have an issue that might indirectly be related to RIU, and perhaps someone has figured out a way around this: 

On both my 12.6 systems with RIU installed and thereby SIP disabled, I'm unable to update to the latest 12.7.1 security update. The update fails immediately upon initiating with the error "“A snapshot is currently set to boot that is not the currently booted snapshot. Reboot to boot to the new snapshot to allow install to this volume.”

I'm suspecting this is because SIP. Web searches indicates that SIP is often the reason for this error, but there seems to be no consensus on why or how to fix it, most results indicate it should be disabled for the update to go through. I have tried to both enable it and disable it, multiple times, no matter what state SIP is in, I'm unable to update to 12.7.1....

So, has anyone of you RIU users generally been able to update your macOS while disabled SIP, and specifically then to 12.7.1 (if you could, then I probably should look elsewhere for the problem)

Thanks for any insights and thanks again for a superb tool.

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)

**Comment by cybrgloom** [comment]
That is awesome, fiiiiinally! This solution works for me (live performances with external screens). Thank you so much for updating this thread with this information - and again re-thanking you for your work with this utility. Cheers!
