### ISSUE TITLE
Can I open/off without restart every time ?

### ISSUE THREAD

**Issue by iciness1009** [cormiertyshawn895/RecordingIndicatorUtility#19]
From the demonstration video, it seems that easily to open and off during recording
but here, I have enter password and restart computer every time
Is there any way let me open/off without restart every time ?
Might be the setting different 
<img width="257" alt="截圖 2023-11-27 上午1 39 23" src="https://github.com/cormiertyshawn895/RecordingIndicatorUtility/assets/66376970/99d515ec-92bc-44d4-b004-04fb563ea846">
?

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
