### ISSUE TITLE
Doesn't work under macOS 12.2.1

### ISSUE THREAD

**Issue by myonlylonely** [cormiertyshawn895/RecordingIndicatorUtility#2]
It doesn't work under macOS 12.2.1, just move the orange dot to another position.
before:
<img width="120" alt="image" src="https://user-images.githubusercontent.com/8188177/157684321-2c73c434-cde2-49ae-ba54-360db6fc300f.png">
after:
<img width="118" alt="image" src="https://user-images.githubusercontent.com/8188177/157684501-7d40193c-cde3-4669-922b-aed8affecd10.png">
I set like this.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/8188177/157684665-1956f4cf-0207-4707-9974-0d040fe60917.png">

**Comment by CodySchrank** [comment]
For me as well.  Also no longer hides the orange dot while in full screen.

**Comment by cormiertyshawn895** [comment]
It looks like you have customized the menu item spacing with Bartender. Can you please try again without Bartender?

**Comment by myonlylonely** [comment]
> It looks like you have customized the menu item spacing with Bartender. Can you please try again without Bartender?

Yes, I already tried that. Still not working.

**Comment by cormiertyshawn895** [comment]
Can you try these:
- Turn off the recording indicator in Recording Indicator Utility
- Open Spotlight, type “Console”, and press return
- In Console, click “Start Streaming”
- In Console, click the search field on the top right corner, type in `RecordingIndicatorUtility`, and press return
- Open Voice Memos, start a new recording, then pause it
- Select all logs in Console and paste them into comments

**Comment by myonlylonely** [comment]
> Can you try these:
> 
> * Turn off the recording indicator in Recording Indicator Utility
> * Open Spotlight, type “Console”, and press return
> * In Console, click “Start Streaming”
> * In Console, click the search field on the top right corner, type in `RecordingIndicatorUtility`, and press return
> * Open Voice Memos, start a new recording, then pause it
> * Select all logs in Console and paste them into comments

May be it is related to the OLCP. OLCP need to patch the system volume to get Nvidia legacy GPU worked, so it is already booted from a non-sealed system snapshot.

**Comment by cormiertyshawn895** [comment]
Based on your feedback, I've improved Recording Indicator Utility to be more reliable. Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by myonlylonely** [comment]
I can confirm that it is now working with macOS 13.2.1, even with OLCP root patched.

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
