### ISSUE TITLE
Security alert that blocked my Apple ID 

### ISSUE THREAD

**Issue by thierry-laval** [cormiertyshawn895/RecordingIndicatorUtility#20]
On my Mac on Sonoma, the SIP was already disabled.
I turn it off for my work as a developer.
I launched your application to remove this icon.
The result was not joking to me, I reactivated the icon with your application.
Everything worked well.
I restarted the system and my Apple account was disabled.
I had to call Apple to request a reactivation of my Apple ID within 24 hours.
According to them, there was a security alert that blocked my Apple ID coming from your app…
Has anyone ever had this?

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
