### ISSUE TITLE
Mac Mini M1 not bootable

### ISSUE THREAD

**Issue by spurin** [cormiertyshawn895/RecordingIndicatorUtility#3]
Hiya,

I tried this on a Mac Mini M1 running 12.3.  I had FileVault enabled so that was disabled and then, both of the csrutil commands were executed in recovery mode.

Rebooted, toggled the Recording Indicator and rebooted.

Unfortunately, after that my system no longer booted and was just given the recovery options.

Fortunately, I was able to rectify by booting back into recovery and toggling the csrutil commands back to enabled.

I’m still keen to get this working.  Any ideas?

Thanks!

**Comment by cormiertyshawn895** [comment]
Hi rpurin,

Based on your feedback, I've improved Recording Indicator Utility to be more reliable. With [the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases), you no longer need to turn off FileVault or `authenticated-root`. Turning off SIP is now enough for Recording Indicator Utility to work its magic. The QR code instruction within the app has also been updated.

Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)

**Comment by spurin** [comment]
Amazing, appreciate you sharing this @cormiertyshawn895 - thank you!
