### ISSUE TITLE
Thank you! Working on Monterey 12.5

### ISSUE THREAD

**Issue by aveotux** [cormiertyshawn895/RecordingIndicatorUtility#5]
Thanks so much for this app.  I used a different solution previously which involved unprotecting system files etc..

Your app is so much better as I have an option to switch Apple's warning off without jeopardising the overall security of the system.

Great work - thanks so much!

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
