### ISSUE TITLE
Quit unexpectedly on Ventura Beta

### ISSUE THREAD

**Issue by Velcorn** [cormiertyshawn895/RecordingIndicatorUtility#6]
I have been using the app without problems on the latest version of Monterey, but since upgrading to the Ventura Beta it gives me the "quit unexpectedly" error and any subsequent attempt to open the app just does nothing. Many thanks for any help in advance!

**Comment by cormiertyshawn895** [comment]
[Recording Indicator Utility 1.3]((https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases)) should resolve this crash on macOS Ventura for Macs with Apple Silicon.

Can you give it a try?

**Comment by Velcorn** [comment]
Sorry for the late reply, I just saw this. Works flawlessly again, thank you very much!

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
