### ISSUE TITLE
Application window not appearing when I updated to macOS v12.5.1

### ISSUE THREAD

**Issue by EnergizerErica** [cormiertyshawn895/RecordingIndicatorUtility#7]
Hi, Tyshawn! Thank you so much for this app. It has helped me a lot.

Recently, after updating to v12.5.1 and disabling csrutil, I tried opening the app, but the app window is not appearing.

Since the default setting of the app is to show the orange dot, just merely opening the app would not turn the indicator off, and I need to actually see the window to slide the setting to off.

Is there a way for me to make the app window appear again?

Thank you so much once again!

**Comment by cormiertyshawn895** [comment]
Can you restart your Mac and try again?

**Comment by EnergizerErica** [comment]
Thank you very much for replying, Tyshawn. I really appreciate it.

I have done that several times to no avail.

After opening the app, when I try to restart, the app actually prevents the computer from restarting unless I quit the app first using the "Force Quit Applications" window.

The only visible part of the app is its menu bar with the app name. When clicking the app name on the menu bar, there is no dropdown menu.

These observations were observed for both v1.1 and v1.2. That's how much I love your app! 😄

Thank you so much for helping us out. Cheers!

**Comment by cormiertyshawn895** [comment]
Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by EnergizerErica** [comment]
Good day, Tyshawn!

Thank you so much for providing the update! The orange dot disappeared again!

I'm so happy! Thank you so much again! I really appreciate this!

Take care!

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
