### ISSUE TITLE
Only works Recording indicator Utility but not other apps like OBS

### ISSUE THREAD

**Issue by Beach77** [cormiertyshawn895/RecordingIndicatorUtility#8]
I followed the instructions and managed to make it work but only for the app itself but when I use OBS for example the orange indicator is still there. I'm on version 1.3.  

EDIT: Forgot to mention I'm using a MacBook Air M1 on Monterey 12.5.1

<img width="1280" alt="Screenshot 2022-09-13 at 12 56 42" src="https://user-images.githubusercontent.com/101499628/189884567-15fc9e98-8950-4507-bf69-d39adfc0d756.png">

**Comment by cormiertyshawn895** [comment]
Based on your feedback, I've improved Recording Indicator Utility to be more reliable. Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)

**Comment by Beach77** [comment]
> In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)

Thanks bro. I don't need it any more, but I'll remember this if I ever need it again.
