### ISSUE TITLE
not working on M1 mac mini with macOS 12.6

### ISSUE THREAD

**Issue by juzala** [cormiertyshawn895/RecordingIndicatorUtility#9]
Application not working on my M1 mac mini with macOS 12.6.

After reboot nothing change - indicator is still in corner :(

**Comment by cormiertyshawn895** [comment]
Based on your feedback, I've improved Recording Indicator Utility to be more reliable. Can you [download the latest update](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/releases) and try again?

**Comment by cormiertyshawn895** [comment]
In macOS Sonoma 14.4 or later, you can hide the recording indicator on external displays without using Recording Indicator Utility. [Learn more ↗](https://support.apple.com/118449)
